modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/Peatral/Better-Spyglass/issues"
license = "Insert License Here"

[[mods]]
modId = "better_spyglass"
version = "${version}"
displayName = "Better Spyglass"
displayURL = "https://github.com/Peatral/Better-Spyglass/"
authors = "Peatral"
description = '''
Improve your spyglass uses by using it from your belt while your friends watch!
'''
logoFile = "assets/better_spyglass/icon.png"

[[dependencies.better_spyglass]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.better_spyglass]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.better_spyglass]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.better_spyglass]]
modId="cloth_config"
type = "required"
versionRange="[15.0,)"
ordering="BEFORE"
side="BOTH"

[[dependencies.better_spyglass]]
modId="curios"
type = "optional"
versionRange="[9.5,10.0)"
ordering="BEFORE"
side="BOTH"

[[mixins]]
config = "better_spyglass.mixins.json"
